# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).

name: CI

on: [push, pull_request] # on all pushes and PRs

jobs:
  dummy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["ros:rolling-ros1-bridge-focal", "ros:foxy-ros1-bridge-focal"]
    container:
      image: ${{ matrix.distro }}
    env:
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
    steps:
      - uses: actions/checkout@v2
      - name: ccache cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.ros_distro }}-${{ matrix.ros_repo }}-${{github.run_id}}
          restore-keys: |
            ccache-${{ matrix.ros_distro }}-${{ matrix.ros_repo }}
      - name: Build ros1-bridge
        run: |
          bash ./build_bridge.sh
          echo $GITHUB_WORKSPACE
          echo ${{ github.workspace }}
          ls
      - name: Test ros1-bridge
        run: |
          bash ./test_bridge.sh
