# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).

name: CI

on: [push, pull_request] # on all pushes and PRs

jobs:
  dummy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["ros:foxy-ros-base-focal"]
    container:
      image: ${{ matrix.distro }}
    env:
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
    steps:
      - uses: actions/checkout@v2
      - name: install ccache
        run: |
          sudo apt-get update -y
          sudo apt-get -qq install ccache
          whereis ccache
          export PATH="/usr/lib/ccache:$PATH"
      - name: ccache cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.distro }}-${{github.run_id}}
          restore-keys: |
            ccache-${{ matrix.distro }}
      - name: ccache stats
        run: ccache -s
      - name: Build workspace
        run: |
          bash ./build_bridge.sh
          echo $GITHUB_WORKSPACE
          echo ${{ github.workspace }}
          ls
      # - name: Test ros1-bridge
      #   run: |
      #     bash ./test_bridge.sh
