# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).

name: CI

on: [push, pull_request] # on all pushes and PRs

jobs:
  dummy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["ros:rolling-ros1-bridge-focal", "ros:foxy-ros1-bridge-focal"]
    container:
      image: ${{ matrix.distro }}
    steps:
      - uses: actions/checkout@v2
      - name: Build ros1-bridge
        run: |
          echo ${{ github.workspace }}
          ls
          bash ./build_bridge.sh
      - name: Test ros1-bridge
        run: |
          bash ./test_bridge.sh
